### ISSUE TITLE
Memory leak after several Drawing tab refreshes

### ISSUE THREAD

**Issue by Zeldruck** [Zeldruck/Albion-Online-ZQRadar#3]
After refreshing the Drawing tab in our browser several times, it creates this warning and starts to lag

EDIT:
It's always after 11 refreshes.
As indicated in the warning.

```
(node:25848) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 packet listeners added to [Cap]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:25848) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 event listeners added to [PhotonPacketParser]. Use emitter.setMaxListeners() to increase limit
(node:25848) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 request listeners added to [PhotonPacketParser]. Use emitter.setMaxListeners() to increase limit
(node:25848) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 response listeners added to [PhotonPacketParser]. Use emitter.setMaxListeners() to increase limit
```

**Comment by Zeldruck** [comment]
Trace warnings

```
(node:6412) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 packet listeners added to [Cap]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:591:17)
    at Cap.addListener (node:events:609:10)
    at WebSocketServer.<anonymous> (E:\Albion-Online-Radar-ZQRadar\app.js:134:5)
    at WebSocketServer.emit (node:events:517:28)
    at WebSocketServer.completeUpgrade (E:\Albion-Online-Radar-ZQRadar\node_modules\ws\lib\websocket-server.js:427:5)
    at WebSocketServer.handleUpgrade (E:\Albion-Online-Radar-ZQRadar\node_modules\ws\lib\websocket-server.js:336:10)
    at Server.upgrade (E:\Albion-Online-Radar-ZQRadar\node_modules\ws\lib\websocket-server.js:112:16)
    at Server.emit (node:events:517:28)
    at onParserExecuteCommon (node:_http_server:915:14)
(node:6412) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 event listeners added to [PhotonPacketParser]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:591:17)
    at PhotonPacketParser.addListener (node:events:609:10)
    at WebSocketServer.<anonymous> (E:\Albion-Online-Radar-ZQRadar\app.js:152:11)
    at WebSocketServer.emit (node:events:517:28)
    at WebSocketServer.completeUpgrade (E:\Albion-Online-Radar-ZQRadar\node_modules\ws\lib\websocket-server.js:427:5)
    at WebSocketServer.handleUpgrade (E:\Albion-Online-Radar-ZQRadar\node_modules\ws\lib\websocket-server.js:336:10)
    at Server.upgrade (E:\Albion-Online-Radar-ZQRadar\node_modules\ws\lib\websocket-server.js:112:16)
    at Server.emit (node:events:517:28)
    at onParserExecuteCommon (node:_http_server:915:14)
(node:6412) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 request listeners added to [PhotonPacketParser]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:591:17)
    at PhotonPacketParser.addListener (node:events:609:10)
    at WebSocketServer.<anonymous> (E:\Albion-Online-Radar-ZQRadar\app.js:161:11)
    at WebSocketServer.emit (node:events:517:28)
    at WebSocketServer.completeUpgrade (E:\Albion-Online-Radar-ZQRadar\node_modules\ws\lib\websocket-server.js:427:5)
    at WebSocketServer.handleUpgrade (E:\Albion-Online-Radar-ZQRadar\node_modules\ws\lib\websocket-server.js:336:10)
    at Server.upgrade (E:\Albion-Online-Radar-ZQRadar\node_modules\ws\lib\websocket-server.js:112:16)
    at Server.emit (node:events:517:28)
    at onParserExecuteCommon (node:_http_server:915:14)
(node:6412) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 response listeners added to [PhotonPacketParser]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:591:17)
    at PhotonPacketParser.addListener (node:events:609:10)
    at WebSocketServer.<anonymous> (E:\Albion-Online-Radar-ZQRadar\app.js:169:11)
    at WebSocketServer.emit (node:events:517:28)
    at WebSocketServer.completeUpgrade (E:\Albion-Online-Radar-ZQRadar\node_modules\ws\lib\websocket-server.js:427:5)
    at WebSocketServer.handleUpgrade (E:\Albion-Online-Radar-ZQRadar\node_modules\ws\lib\websocket-server.js:336:10)
    at Server.upgrade (E:\Albion-Online-Radar-ZQRadar\node_modules\ws\lib\websocket-server.js:112:16)
    at Server.emit (node:events:517:28)
    at onParserExecuteCommon (node:_http_server:915:14)
```

**Comment by lazycoderz1** [comment]
@Zeldruck I have some update for this in this PR https://github.com/Zeldruck/Albion-Online-ZQRadar/pull/5
please help to review it if you have time
